'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class empleadores

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents ButtonEmp As Button
    Protected WithEvents TextFechaSol As TextBox
    Protected WithEvents TextNombreEmpresa As TextBox
    Protected WithEvents TextRazon As TextBox
    Protected WithEvents TextRut As TextBox
    Protected WithEvents TextActividad As TextBox
    Protected WithEvents TextDireccion As TextBox
    Protected WithEvents TextFono As TextBox
    Protected WithEvents TextEmail As TextBox
    Protected WithEvents TextNombreSol As TextBox
    Protected WithEvents TextCargoSol As TextBox
    Protected WithEvents TextFonoSol As TextBox
    Protected WithEvents TextEmailSol As TextBox
    Protected WithEvents TextCargo As TextBox
    Protected WithEvents TextArea As TextBox
    Protected WithEvents TextDescripcionCargo As TextBox
    Protected WithEvents TextPerfilPostulante As TextBox
    Protected WithEvents DropDownListSexo As DropDownList
    Protected WithEvents DropDownListexperiencia As DropDownList
    Protected WithEvents TextRangoEdad As TextBox
    Protected WithEvents DropDownListNivelEst As DropDownList
    Protected WithEvents TextConocimiento As TextBox
    Protected WithEvents TextSueldoBru As TextBox
    Protected WithEvents TextSueldoLiq As TextBox
    Protected WithEvents DropDownListTipoContrato As DropDownList
    Protected WithEvents TextLugarTrab As TextBox
    Protected WithEvents TextHorarioTrab As TextBox
    Protected WithEvents TextFechaContratacion As TextBox
    Protected WithEvents TextLugarEnt As TextBox
    Protected WithEvents TextHoraEnt As TextBox
    Protected WithEvents TextFechaEnt As TextBox
    Protected WithEvents TextNumeroVac As TextBox
    Protected WithEvents TextNumeroPost As TextBox
    Protected WithEvents CheckCurriculum As CheckBox
    Protected WithEvents CheckCedula As CheckBox
    Protected WithEvents CheckCertiEstudios As CheckBox
    Protected WithEvents CheckCertiTitulo As CheckBox
    Protected WithEvents CheckCertiAntecedentes As CheckBox
    Protected WithEvents CheckLicenciaCond As CheckBox
    Protected WithEvents CheckCertiResidencia As CheckBox
    Protected WithEvents CheckUltimoFiniquito As CheckBox
    Protected WithEvents CheckCartaRef As CheckBox
    Protected WithEvents TextObs As TextBox
    Protected WithEvents Mensaje As Label

End Class
