'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class adm_modificando_capacitacion

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents BotonModificarCap As Button
    Protected WithEvents TextTituloModCap As TextBox
    Protected WithEvents TextFechaModCap As TextBox
    Protected WithEvents TextDescripcionModCap As TextBox
    Protected WithEvents FileUpload1 As FileUpload
End Class
