'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class adm_modificando_oferta

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents BotonModificarOfe As Button
    Protected WithEvents TextTituloModOfe As TextBox
    Protected WithEvents TextFechaModOfe As TextBox
    Protected WithEvents TextDescripcionModOfe As TextBox
    Protected WithEvents FileUpload1 As FileUpload
End Class
